---
title: "Gini_script"
author: "Samuel dos Santos Rodrigues"
format:
  html:
    embed-resources: true
    toc: true
    toc-location: left
    toc-depth: 3
    number-sections: true
    code-fold: true
    code-tools: true
    df-print: paged
    fig-cap-location: top
    fig-align: center
    theme: cosmo
    highlight-style: github
    smooth-scroll: true
    anchor-sections: true
lang: pt-BR
editor: visual
---

```{r}

if (!require("pacman")) install.packages("pacman")

pacman::p_load(
  readxl,
  dplyr,
  tidyr,
  writexl,
  openxlsx,
  data.table,
  DescTools,
  rio,
  janitor,
  knitr
)

```

```{r}

# função para calcular gini:

gini_coluna <- function(coluna) {
  resultado <- DescTools::Gini(coluna,
                               unbiased = TRUE, # usar para n pequeno (>50)
                               na.rm = TRUE,
                               conf.level = 0.95
                               )
  return(resultado)
}

# função para calcular a razão 20/20:

r20_20_coluna <- function(coluna){
  coluna <- coluna[!is.na(coluna)]
  coluna_ordenada <- sort(coluna)
  n <- length(coluna)
  n_20percent <- ceiling(n * 0.2)
  
  media_maiores <- mean(tail(coluna_ordenada, n_20percent))
  media_menores <- mean(head(coluna_ordenada, n_20percent))
  
  resultado <- media_maiores / media_menores
  return(resultado)
}

# função para calcular o coeficiente de variação:

cv_coluna <- function(coluna){
  coluna <- coluna[!is.na(coluna)]
  cv <- sd(coluna) / mean(coluna) * 100
  return(cv)
}

```

```{r}

# definir anos:

anos <- 2023:2025

# Selecionar qual per capita quer rodar:

# Per capita dos afastamentos curtos:
caminho_ac <- "2.metadata/percapita/ac/percapita_ac_2022_2025.xlsx"

# Per capita dos afastamentos longos:
caminho_al <- "2.metadata/percapita/al/percapita_al_2022_2025.xlsx"

# Per capita dos auxilios financeiros:
caminho_af <- "2.metadata/percapita/af/percapita_af_2023_2025.xlsx"

# Rodar com o per capita desejado:

dados <- rio::import(caminho_af) %>% 
  select("2023":"2025")
  

# iniciar data frame para armazenar os resultados:

resultados_df <- data.frame(
  Ano = integer(),
  Gini = numeric(),
  Gini_lower = numeric(),
  Gini_upper = numeric(),
  Razao20_20 = numeric(),
  CV = numeric()
)


  
```

```{r}

# loop para calcular ano a ano:

for (ano in anos) {
  nome_coluna <- as.character(ano)
  
  if (nome_coluna %in% colnames(dados)) {
    coluna_vetorizada <- dados %>%
      dplyr::pull(!!nome_coluna)
    
    coluna_vetorizada <- as.numeric(coluna_vetorizada)
    
    resultado_gini <- gini_coluna(coluna_vetorizada)
    resultado_razao20 <- r20_20_coluna(coluna_vetorizada)
    resultado_cv <- cv_coluna(coluna_vetorizada)
    
    nova_linha <- data.frame(
      Ano = ano,
      Gini = resultado_gini["gini"],
      Gini_lower = resultado_gini["lwr.ci"],
      Gini_upper = resultado_gini["upr.ci"],
      Razao20_20 = resultado_razao20,
      CV = resultado_cv
    )
    rownames(nova_linha) <- NULL
    resultados_df <- rbind(resultados_df, nova_linha)
  
  } else {
    warning(paste("A coluna", nome_coluna, "não foi encontrada no arquivo."))
  }
}

# ver resultado final:

print(resultados_df)

# salvar:

rio::export(resultados_df, "3.outputs/gini/af/gini_af.xlsx")

```
